### ISSUE TITLE
I found some bugs but I don't know if anyone is listening

### ISSUE THREAD

**Issue by fwgreen** [forax/valuetype-lambda#2]
I'm very sorry to bother you with this.  I've run into two bugs so far and I submitted the first one over a week ago to `amber-dev`.  I received an automated response immediately but nothing since.  I'm assuming the moderator is unavailable and so, as only members may post to the group, I'm hoping you might forward them to the list for me.  I don't need attribution, I just want these additions to be stable enough to be preview features in Java 12.

I think this shouldn't compile let alone run without a break statement.  Though that is my impression from reading the JEP.
```Java
public class SwitchBug {
    
    static String hold(String item) -> switch(item) {
      case String s -> { System.out.println(s); }
      default -> "temp";
    }

    public static void main(String[] args) {
        System.out.println(hold("bug"));
    }
}
```
but it outputs
```
bug
temp
```
The second is the one I reported over a week ago; it compiles and crashes at runtime (Maybe someone is already working on it and the moderator was too busy to reply).
```Java
import java.util.stream.Stream;

public class KindOfBlue {

  static Shade shade(Blue b) -> switch (b) { //Adding <Blue> prevents the crash
    case Azure a-> a.shade;
    case Royal r -> r.shade;
    case IKB i -> i.shade;
    default -> throw new IllegalArgumentException("Unknown color");
  }

  public static void main(String[] args) {
    var colors = Stream.of(new Royal(Shade.MEDIUM), new IKB(Shade.DARK), new Azure(Shade.LIGHT));
    colors.map(KindOfBlue::shade).forEach(System.out::println);
  }
}

interface Blue;
record Royal(Shade shade) implements Blue;
record IKB(Shade shade) implements Blue;
record Azure(Shade shade) implements Blue;

enum Shade {
  LIGHT, MEDIUM, DARK
}
```
the output
```
Exception in thread "main" java.lang.BootstrapMethodError: bootstrap method initialization exception
        at java.base/java.lang.invoke.BootstrapMethodInvoker.invoke(BootstrapMethodInvoker.java:194)
        at java.base/java.lang.invoke.CallSite.makeSite(CallSite.java:307)
        at java.base/java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(MethodHandleNatives.java:258)
        at java.base/java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:248)
        at KindOfBlue.main(KindOfBlue.java:14)
Caused by: java.lang.invoke.LambdaConversionException: Type mismatch for lambda argument 0: class java.lang.AbstractRecord is not convertible to interface Blue
        at java.base/java.lang.invoke.AbstractValidatingLambdaMetafactory.validateMetafactoryArgs(AbstractValidatingLambdaMetafactory.java:279)
        at java.base/java.lang.invoke.LambdaMetafactory.metafactory(LambdaMetafactory.java:328)
        at java.base/java.lang.invoke.BootstrapMethodInvoker.invoke(BootstrapMethodInvoker.java:127)
        at java.base/java.lang.invoke.CallSite.makeSite(CallSite.java:307)
        at java.base/java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(MethodHandleNatives.java:258)
        at java.base/java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:248)
        at KindOfBlue.main(KindOfBlue.java:14)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at jdk.compiler/com.sun.tools.javac.launcher.Main.execute(Main.java:415)
        at jdk.compiler/com.sun.tools.javac.launcher.Main.run(Main.java:192)
        at jdk.compiler/com.sun.tools.javac.launcher.Main.main(Main.java:132)
```
Adding a type parameter to the shade method prevents the crash; also changing the records to classes prevents the crash.  

Thanks for anything you can do here.  I would gladly wait patiently if I was certain that there was someone at the other end of my message.

**Comment by forax** [comment]
Hi,
you don't bother me at all,
i've not seen your mails on amber-dev, that's why you have not received any replies.

Did you first subscribe on amber-dev before sending an email to it ?
https://mail.openjdk.java.net/mailman/listinfo/amber-dev

**Comment by forax** [comment]
Your second example has nothing to do with the records or the concise method bodies, i believe it's a bug in the current version of javac.
The type of the Stream is the intersection type C & I, which is erased as C, given that f takes an I, the 
compiler has to generate a bridge method that does the cast to I like this
  String lambda$1(C c) { f((I)c); }
and then create the method reference on lambda$1 instead of f.

```
public class RecordBadType {
  interface  I {}
  static abstract class C { }
  static class A extends C implements I { }
  static class B extends C implements I { }
  
  static String f(I i) { return null; }

  public static void main(String[] args) {
    Stream.of(new A(), new B())
      .map(RecordBadType::f)   // here the compiler should generate a bridge method 
      .forEach(System.out::println);
  }
}
```

**Comment by forax** [comment]
I've reported the two bugs to the their corresponding mailing lists (amber-dev and compiler-dev).
http://mail.openjdk.java.net/pipermail/amber-dev/2018-October/003601.html
http://mail.openjdk.java.net/pipermail/compiler-dev/2018-October/012569.html
